import { Card } from '@buddy/ui-components';

export function PrivacyScreen() {
  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: '12px' }}>
      <div>
        <h3 style={{ margin: '0 0 4px 0', fontSize: '16px', color: 'var(--buddy-text-main, #0f172a)' }}>
          Privacy Architecture & Transparency
        </h3>
        <p style={{ margin: 0, fontSize: '12px', color: 'var(--buddy-text-muted, #64748b)' }}>
          Audited local-first privacy guarantees — no servers, no cloud tracking, ₹0 cost
        </p>
      </div>

      <div
        style={{
          padding: '14px',
          backgroundColor: 'rgba(16, 185, 129, 0.08)',
          border: '1px solid rgba(16, 185, 129, 0.25)',
          borderRadius: 'var(--buddy-radius-md, 8px)',
        }}
      >
        <div style={{ display: 'flex', alignItems: 'center', gap: '8px', marginBottom: '6px' }}>
          <span style={{ fontSize: '18px' }}>🔒</span>
          <span style={{ fontSize: '14px', fontWeight: 700, color: '#065f46' }}>
            100% Local Storage Architecture
          </span>
        </div>
        <p style={{ margin: 0, fontSize: '12px', color: '#047857', lineHeight: 1.5 }}>
          All data generated by Buddy Shield, Focus Mode, Watch-Time Engine, and Buddy Pet is stored
          exclusively on your device in standard <code>chrome.storage.local</code>. Buddy maintains zero
          external servers, collects zero telemetry, and performs zero cloud synchronization.
        </p>
      </div>

      <Card title="What Buddy Measures">
        <ul style={{ margin: 0, paddingLeft: '18px', fontSize: '12px', color: 'var(--buddy-text-muted, #64748b)', lineHeight: 1.6 }}>
          <li>
            <strong>Active Time:</strong> Milliseconds an active browser tab is in the foreground and receiving user focus.
          </li>
          <li>
            <strong>Media Playback:</strong> HTML5 video and audio play/pause state timestamps for watch-time tracking.
          </li>
          <li>
            <strong>Blocked Network Requests:</strong> Aggregated numeric counts of ads and trackers intercepted by Shield.
          </li>
          <li>
            <strong>Focus Sessions:</strong> Start and end timestamps of intentional Focus Mode blocks.
          </li>
          <li>
            <strong>Rapid Scroll Signals:</strong> Rate of page scrolls used to detect doomscroll loops on supported feeds.
          </li>
        </ul>
      </Card>

      <Card title="What Buddy NEVER Collects or Stores">
        <ul style={{ margin: 0, paddingLeft: '18px', fontSize: '12px', color: '#991b1b', lineHeight: 1.6 }}>
          <li><strong>NO Browsing History:</strong> Specific page URLs and paths are never recorded.</li>
          <li><strong>NO Page Titles:</strong> Article titles, video titles, or account names are never stored.</li>
          <li><strong>NO Private Messages:</strong> DMs, chat contents, and input fields are never accessed.</li>
          <li><strong>NO Page Contents:</strong> HTML, text, or DOM nodes are never scraped or exported.</li>
          <li><strong>NO Keystrokes or Passwords:</strong> Never intercepted or logged.</li>
          <li><strong>NO Screenshots:</strong> No visual captures of your screen are ever taken.</li>
        </ul>
      </Card>

      <Card title="Zero-Cost & Offline Guarantee">
        <div style={{ fontSize: '12px', color: 'var(--buddy-text-muted, #64748b)', lineHeight: 1.5 }}>
          Buddy is engineered to operate completely offline. Even when your computer has no internet
          connection, all dashboard analytics, mood score calculations, habit streaks, and request
          blocking rules function seamlessly with zero latency.
        </div>
      </Card>
    </div>
  );
}
